/**
 ******************************************************************************
 * @file      startup_stm32f103rbtx.s
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32F103RBTx device vector table for GCC toolchain.
 *            This module performs:
 *                - Set the initial SP
 *                - Set the initial PC == Reset_Handler,
 *                - Set the vector table entries with the exceptions ISR address
 *                - Branches to main in the C library (which eventually
 *                  calls main()).
 ******************************************************************************
 * @attention
 *
 * Copyright (c) ${year} STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

.syntax unified
.cpu cortex-m3
.fpu softvfp
.thumb

.include "stm32f10x.s"

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss

/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0          /* set stack pointer */
 ///////////////////////////////

  ldr	r2, =PERIPH_BB_BASE+ \
				(RCC_APB2ENR-PERIPH_BASE)*32 + \
				4*4 @ вычисляем адрес для BitBanding 4-го бита регистра RCC_APB2ENR
  mov	r3, #1@ включаем тактирование порта C (в 4-й бит RCC_APB2ENR пишем '1`)
  str 	r3, [r2]@ загружаем это значение

  ldr	r2, =GPIOC_CRL	@ адрес порта
  mov	r3, #0x03	@ 4-битная маска настроек для Output mode 50mHz, Push-Pull ("0011")
  ldr	r4, [r2]
  bfi	r4, r3, #8, #4	@ скопировать биты маски в позицию pin2
  bfi	r4, r3, #12, #4	@ скопировать биты маски в позицию pin3
  bfi	r4, r3, #16, #4	@ скопировать биты маски в позицию pin4
  bfi	r4, r3, #20, #4	@ скопировать биты маски в позицию pin5
  bfi	r4, r3, #24, #4	@ скопировать биты маски в позицию pin6
  str	r4, [r2]	@ загрузить результат в регистр настройки порта

  ldr	r2, =GPIOC_CRH	@ адрес порта
  mov	r3, #0x03	@ 4-битная маска настроек для Output mode 50mHz, Push-Pull ("0011")
  ldr	r4, [r2]
  bfi	r4, r3, #0, #4	@ скопировать биты маски в позицию pin8
  bfi	r4, r3, #4, #4	@ скопировать биты маски в позицию pin9
  bfi	r4, r3, #8, #4	@ скопировать биты маски в позицию pin10
  bfi	r4, r3, #12, #4 @ скопировать биты маски в позицию pin11
  mov	r3, #0x08 @  4-битная маска настроек для Input mode с подтяжкой, Push-Pull ("1000")
  bfi	r4, r3, #20, #4 @ скопировать биты маски в позицию pin13 (кнопка)
  str	r4, [r2]	@ загрузить результат в регистр настройки порта

  ldr	r2, =GPIOC_BSRR

  ldr	r3, =GPIO_BSRR_BS13 @подтяжка пина с кнопкой к 1
  str	r3, [r2]

  mov	r5, #0x0
  mov 	r6, #0x0
  mov 	r7, #0x0

  loop:
		@ вычисляем адрес для BitBanding 13-го бита регистра GPIOC_IDR
  		ldr 	r0, =(PERIPH_BB_BASE + (GPIOC_IDR - PERIPH_BASE) * 32 + 13 * 4)
		ldr		r1, [r0]


  		ldr		r3, =GPIO_BSRR_BS10 @ dig1 ON
  		str		r3, [r2]
  		ldr		r3, =GPIO_BSRR_BR11 @ dig2 OFF
  		str		r3, [r2]

  		bl		digit1
  		bl		delay

  		ldr		r3, =GPIO_BSRR_BR10 @ dig1 OFF
  		str		r3, [r2]
  		ldr		r3, =GPIO_BSRR_BS11 @ dig2 ON
  		str		r3, [r2]

  		cmp		r5, #0xA
  		itt		eq
  		moveq 	r5, #0x0
  		addeq	r6, #0x1

  		bl		digit2
  		bl		delay

  		cmp		r1, #0
		beq		loop

  		cmp		r7, #0x20
  		itt		eq
  		addeq	r5, #0x1
  		moveq 	r7, #0x0

		add		r7, #0x1

  		b 		loop

  digit1:
  		push 	{r2, r3, r5, lr}

  		ldr		r2, =GPIOC_BSRR

  		cmp		r5, #0
  		case0_1:
  			bne		case1_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR9 //g
  			str		r3, [r2]
  			b		endcase

  		case1_1:
  			cmp r5, #0x1
  			bne		case2_1
  			ldr		r3, =GPIO_BSRR_BR2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR9 //g
  			str		r3, [r2]
  			b		endcase

  		case2_1:
  			cmp r5, #0x2
  			bne		case3_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case3_1:

  			cmp r5, #0x3
  			bne		case4_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case4_1:
  			cmp r5, #0x4
  			bne		case5_1
  			ldr		r3, =GPIO_BSRR_BR2  //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case5_1:
  			cmp r5, #0x5
  			bne		case6_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case6_1:
  			cmp r5, #0x6
  			bne		case7_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case7_1:
  			cmp	r5, #0x7
  			bne		case8_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR9 //g
  			str		r3, [r2]
  			b		endcase

  		case8_1:
  			cmp	r5, #0x8
  			bne		case9_1
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case9_1:
  			cmp	r5, #0x9
  			bne		default
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		default:
  			b		endcase

  		endcase:
  			pop		{r2, r3, r5, lr}
  			bx	 	lr

  digit2:
  		push 	{r2, r3, r5, lr}

  		ldr		r2, =GPIOC_BSRR

  		cmp		r6, #0
  		case0_2:
  			bne		case1_2
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR9 //g
  			str		r3, [r2]
  			b		endcase

  		case1_2:
  			cmp r6, #0x1
  			bne		case2_2
  			ldr		r3, =GPIO_BSRR_BR2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR9 //g
  			str		r3, [r2]
  			b		endcase

  		case2_2:
  			cmp r6, #0x2
  			bne		case3_2
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]
  			b		endcase

  		case3_2:
  			cmp r6, #0x3
  			bne		default
  			ldr		r3, =GPIO_BSRR_BS2 //a
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS3 //b
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS4 //c
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS5 //d
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR6 //e
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BR8 //f
  			str		r3, [r2]
  			ldr		r3, =GPIO_BSRR_BS9 //g
  			str		r3, [r2]

			cmp		r7, #0x20
  			ittt	eq
  			moveq 	r5, #0x0
 			moveq 	r6, #0x0
 			moveq	r7, #0x0

  			b		endcase

  delay:									@ Подпрограмма задержки
		push	{r2}						@ Загружаем в стек R0, т.к. его значение будем менять
		ldr		r2, =0x5555					@ псевдоинструкция Thumb (загрузить константу в регистр)
  	delay_loop:
		subs	r2, #1						@ SUB с установкой флагов результата
		it 		NE
		bne		delay_loop					@ переход, если Z!=0 (результат вычитания не равен нулю)
		pop		{r2}						@ Выгружаем из стека R0
		bx		lr							@ выход из подпрограммы (переход к адресу в регистре LR - вершина стека)


 ///////////////////////////////
  .size Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler

/******************************************************************************
*
* The STM32F103RBTx vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/
  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
  .size g_pfnVectors, .-g_pfnVectors

g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word NMI_Handler
  .word HardFault_Handler
  .word	MemManage_Handler
  .word	BusFault_Handler
  .word	UsageFault_Handler
  .word	0
  .word	0
  .word	0
  .word	0
  .word	SVC_Handler
  .word	DebugMon_Handler
  .word	0
  .word	PendSV_Handler
  .word	SysTick_Handler
  .word	WWDG_IRQHandler           			/* Window Watchdog interrupt                        */
  .word	PVD_IRQHandler            			/* PVD through EXTI line detection interrupt        */
  .word	TAMPER_IRQHandler         			/* Tamper interrupt                                 */
  .word	RTC_IRQHandler            			/* RTC global interrupt                             */
  .word	FLASH_IRQHandler          			/* Flash global interrupt                           */
  .word	RCC_IRQHandler            			/* RCC global interrupt                             */
  .word	EXTI0_IRQHandler          			/* EXTI Line0 interrupt                             */
  .word	EXTI1_IRQHandler          			/* EXTI Line1 interrupt                             */
  .word	EXTI2_IRQHandler          			/* EXTI Line2 interrupt                             */
  .word	EXTI3_IRQHandler          			/* EXTI Line3 interrupt                             */
  .word	EXTI4_IRQHandler          			/* EXTI Line4 interrupt                             */
  .word	DMA1_Channel1_IRQHandler  			/* DMA1 Channel1 global interrupt                   */
  .word	DMA1_Channel2_IRQHandler  			/* DMA1 Channel2 global interrupt                   */
  .word	DMA1_Channel3_IRQHandler  			/* DMA1 Channel3 global interrupt                   */
  .word	DMA1_Channel4_IRQHandler  			/* DMA1 Channel4 global interrupt                   */
  .word	DMA1_Channel5_IRQHandler  			/* DMA1 Channel5 global interrupt                   */
  .word	DMA1_Channel6_IRQHandler  			/* DMA1 Channel6 global interrupt                   */
  .word	DMA1_Channel7_IRQHandler  			/* DMA1 Channel7 global interrupt                   */
  .word	ADC1_2_IRQHandler         			/* ADC1 and ADC2 global interrupt                   */
  .word	USB_HP_CAN_TX_IRQHandler  			/* USB High Priority or CAN TX interrupts           */
  .word	USB_LP_CAN_RX0_IRQHandler 			/* USB Low Priority or CAN RX0 interrupts           */
  .word	CAN_RX1_IRQHandler        			/* CAN RX1 interrupt                                */
  .word	CAN_SCE_IRQHandler        			/* CAN SCE interrupt                                */
  .word	EXTI9_5_IRQHandler        			/* EXTI Line[9:5] interrupts                        */
  .word	TIM1_BRK_IRQHandler       			/* TIM1 Break interrupt                             */
  .word	TIM1_UP_IRQHandler        			/* TIM1 Update interrupt                            */
  .word	TIM1_TRG_COM_IRQHandler   			/* TIM1 Trigger and Commutation interrupts          */
  .word	TIM1_CC_IRQHandler        			/* TIM1 Capture Compare interrupt                   */
  .word	TIM2_IRQHandler           			/* TIM2 global interrupt                            */
  .word	TIM3_IRQHandler           			/* TIM3 global interrupt                            */
  .word	TIM4_IRQHandler           			/* TIM4 global interrupt                            */
  .word	I2C1_EV_IRQHandler        			/* I2C1 event interrupt                             */
  .word	I2C1_ER_IRQHandler        			/* I2C1 error interrupt                             */
  .word	I2C2_EV_IRQHandler        			/* I2C2 event interrupt                             */
  .word	I2C2_ER_IRQHandler        			/* I2C2 error interrupt                             */
  .word	SPI1_IRQHandler           			/* SPI1 global interrupt                            */
  .word	SPI2_IRQHandler           			/* SPI2 global interrupt                            */
  .word	USART1_IRQHandler         			/* USART1 global interrupt                          */
  .word	USART2_IRQHandler         			/* USART2 global interrupt                          */
  .word	USART3_IRQHandler         			/* USART3 global interrupt                          */
  .word	EXTI15_10_IRQHandler      			/* EXTI Line[15:10] interrupts                      */
  .word	RTCAlarm_IRQHandler       			/* RTC Alarms through EXTI line interrupt           */
  .word	0                         			/* Reserved                                         */
  .word	TIM8_BRK_IRQHandler       			/* TIM8 Break interrupt                             */
  .word	TIM8_UP_IRQHandler        			/* TIM8 Update interrupt                            */
  .word	TIM8_TRG_COM_IRQHandler   			/* TIM8 Trigger and Commutation interrupts          */
  .word	TIM8_CC_IRQHandler        			/* TIM8 Capture Compare interrupt                   */
  .word	ADC3_IRQHandler           			/* ADC3 global interrupt                            */
  .word	FSMC_IRQHandler           			/* FSMC global interrupt                            */
  .word	SDIO_IRQHandler           			/* SDIO global interrupt                            */
  .word	TIM5_IRQHandler           			/* TIM5 global interrupt                            */
  .word	SPI3_IRQHandler           			/* SPI3 global interrupt                            */
  .word	UART4_IRQHandler          			/* UART4 global interrupt                           */
  .word	UART5_IRQHandler          			/* UART5 global interrupt                           */
  .word	TIM6_IRQHandler           			/* TIM6 global interrupt                            */
  .word	TIM7_IRQHandler           			/* TIM7 global interrupt                            */
  .word	DMA2_Channel1_IRQHandler  			/* DMA2 Channel1 global interrupt                   */
  .word	DMA2_Channel2_IRQHandler  			/* DMA2 Channel2 global interrupt                   */
  .word	DMA2_Channel3_IRQHandler  			/* DMA2 Channel3 global interrupt                   */
  .word	DMA2_Channel4_5_IRQHandler			/* DMA2 Channel4 and DMA2 Channel5 global interrupt */

/*******************************************************************************
*
* Provide weak aliases for each Exception handler to the Default_Handler.
* As they are weak aliases, any function with the same name will override
* this definition.
*
*******************************************************************************/

	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

	.weak	MemManage_Handler
	.thumb_set MemManage_Handler,Default_Handler

	.weak	BusFault_Handler
	.thumb_set BusFault_Handler,Default_Handler

	.weak	UsageFault_Handler
	.thumb_set UsageFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	DebugMon_Handler
	.thumb_set DebugMon_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	.weak	WWDG_IRQHandler
	.thumb_set WWDG_IRQHandler,Default_Handler

	.weak	PVD_IRQHandler
	.thumb_set PVD_IRQHandler,Default_Handler

	.weak	TAMPER_IRQHandler
	.thumb_set TAMPER_IRQHandler,Default_Handler

	.weak	RTC_IRQHandler
	.thumb_set RTC_IRQHandler,Default_Handler

	.weak	FLASH_IRQHandler
	.thumb_set FLASH_IRQHandler,Default_Handler

	.weak	RCC_IRQHandler
	.thumb_set RCC_IRQHandler,Default_Handler

	.weak	EXTI0_IRQHandler
	.thumb_set EXTI0_IRQHandler,Default_Handler

	.weak	EXTI1_IRQHandler
	.thumb_set EXTI1_IRQHandler,Default_Handler

	.weak	EXTI2_IRQHandler
	.thumb_set EXTI2_IRQHandler,Default_Handler

	.weak	EXTI3_IRQHandler
	.thumb_set EXTI3_IRQHandler,Default_Handler

	.weak	EXTI4_IRQHandler
	.thumb_set EXTI4_IRQHandler,Default_Handler

	.weak	DMA1_Channel1_IRQHandler
	.thumb_set DMA1_Channel1_IRQHandler,Default_Handler

	.weak	DMA1_Channel2_IRQHandler
	.thumb_set DMA1_Channel2_IRQHandler,Default_Handler

	.weak	DMA1_Channel3_IRQHandler
	.thumb_set DMA1_Channel3_IRQHandler,Default_Handler

	.weak	DMA1_Channel4_IRQHandler
	.thumb_set DMA1_Channel4_IRQHandler,Default_Handler

	.weak	DMA1_Channel5_IRQHandler
	.thumb_set DMA1_Channel5_IRQHandler,Default_Handler

	.weak	DMA1_Channel6_IRQHandler
	.thumb_set DMA1_Channel6_IRQHandler,Default_Handler

	.weak	DMA1_Channel7_IRQHandler
	.thumb_set DMA1_Channel7_IRQHandler,Default_Handler

	.weak	ADC1_2_IRQHandler
	.thumb_set ADC1_2_IRQHandler,Default_Handler

	.weak	USB_HP_CAN_TX_IRQHandler
	.thumb_set USB_HP_CAN_TX_IRQHandler,Default_Handler

	.weak	USB_LP_CAN_RX0_IRQHandler
	.thumb_set USB_LP_CAN_RX0_IRQHandler,Default_Handler

	.weak	CAN_RX1_IRQHandler
	.thumb_set CAN_RX1_IRQHandler,Default_Handler

	.weak	CAN_SCE_IRQHandler
	.thumb_set CAN_SCE_IRQHandler,Default_Handler

	.weak	EXTI9_5_IRQHandler
	.thumb_set EXTI9_5_IRQHandler,Default_Handler

	.weak	TIM1_BRK_IRQHandler
	.thumb_set TIM1_BRK_IRQHandler,Default_Handler

	.weak	TIM1_UP_IRQHandler
	.thumb_set TIM1_UP_IRQHandler,Default_Handler

	.weak	TIM1_TRG_COM_IRQHandler
	.thumb_set TIM1_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM1_CC_IRQHandler
	.thumb_set TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM3_IRQHandler
	.thumb_set TIM3_IRQHandler,Default_Handler

	.weak	TIM4_IRQHandler
	.thumb_set TIM4_IRQHandler,Default_Handler

	.weak	I2C1_EV_IRQHandler
	.thumb_set I2C1_EV_IRQHandler,Default_Handler

	.weak	I2C1_ER_IRQHandler
	.thumb_set I2C1_ER_IRQHandler,Default_Handler

	.weak	I2C2_EV_IRQHandler
	.thumb_set I2C2_EV_IRQHandler,Default_Handler

	.weak	I2C2_ER_IRQHandler
	.thumb_set I2C2_ER_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2_IRQHandler
	.thumb_set SPI2_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART2_IRQHandler
	.thumb_set USART2_IRQHandler,Default_Handler

	.weak	USART3_IRQHandler
	.thumb_set USART3_IRQHandler,Default_Handler

	.weak	EXTI15_10_IRQHandler
	.thumb_set EXTI15_10_IRQHandler,Default_Handler

	.weak	RTCAlarm_IRQHandler
	.thumb_set RTCAlarm_IRQHandler,Default_Handler

	.weak	TIM8_BRK_IRQHandler
	.thumb_set TIM8_BRK_IRQHandler,Default_Handler

	.weak	TIM8_UP_IRQHandler
	.thumb_set TIM8_UP_IRQHandler,Default_Handler

	.weak	TIM8_TRG_COM_IRQHandler
	.thumb_set TIM8_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM8_CC_IRQHandler
	.thumb_set TIM8_CC_IRQHandler,Default_Handler

	.weak	ADC3_IRQHandler
	.thumb_set ADC3_IRQHandler,Default_Handler

	.weak	FSMC_IRQHandler
	.thumb_set FSMC_IRQHandler,Default_Handler

	.weak	SDIO_IRQHandler
	.thumb_set SDIO_IRQHandler,Default_Handler

	.weak	TIM5_IRQHandler
	.thumb_set TIM5_IRQHandler,Default_Handler

	.weak	SPI3_IRQHandler
	.thumb_set SPI3_IRQHandler,Default_Handler

	.weak	UART4_IRQHandler
	.thumb_set UART4_IRQHandler,Default_Handler

	.weak	UART5_IRQHandler
	.thumb_set UART5_IRQHandler,Default_Handler

	.weak	TIM6_IRQHandler
	.thumb_set TIM6_IRQHandler,Default_Handler

	.weak	TIM7_IRQHandler
	.thumb_set TIM7_IRQHandler,Default_Handler

	.weak	DMA2_Channel1_IRQHandler
	.thumb_set DMA2_Channel1_IRQHandler,Default_Handler

	.weak	DMA2_Channel2_IRQHandler
	.thumb_set DMA2_Channel2_IRQHandler,Default_Handler

	.weak	DMA2_Channel3_IRQHandler
	.thumb_set DMA2_Channel3_IRQHandler,Default_Handler

	.weak	DMA2_Channel4_5_IRQHandler
	.thumb_set DMA2_Channel4_5_IRQHandler,Default_Handler

	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectonics *****END OF FILE****/
